### ISSUE TITLE
Thesmi in the last line of the script block is not recognized

### ISSUE THREAD

**Issue by kecrily** [ota-meshi/eslint-plugin-astro#102]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.23.0

### What version of `eslint-plugin-astro` are you using?

0.18.0

### What did you do?

<details>
<summary>Configuration</summary>

```js
module.exports = {
  /** @type { import('eslint').Linter.Config } */
  rules: {
    semi: ['error', 'never'],
  },
  overrides: [
    {
      files: ['*.astro'],
      parser: 'astro-eslint-parser',
    },
  ],
}
```
</details>

```astro
---
console.log('Hello 1')
console.log('Hello 2');
---
```

### What did you expect to happen?

Recognize the semi of the last statement line like a normal js file.

### What actually happened?

Cannot recognize the last line of the statement

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/node-qjzrj8?file=index.astro

Run `pnpm lint` to see the result

### Additional comments

I think it's a parser error, but I'm not sure.

**Comment by ota-meshi** [comment]
Thank you for posting the issue. Apparently the `semi` rule doesn't recognize `.astro`'s `---` token. Therefore it is incompatible with ` semi: ['error', 'never']`. I think we need to create an extended `semi` rule.v
