### ISSUE TITLE
Format HTML template without Prettier

### ISSUE THREAD

**Issue by essarn** [ota-meshi/eslint-plugin-astro#112]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

v8.24.0

### What version of `eslint-plugin-astro` are you using?

0.19.0

### What did you do?

<details>
<summary>Configuration ESLint</summary>

```json
{
  "extends": ["plugin:astro/recommended", "@antfu"],
  "overrides": [
    {
      "files": ["*.astro"],
      "parser": "astro-eslint-parser",
      "parserOptions": {
        "parser": "@typescript-eslint/parser",
        "extraFileExtensions": [".astro"]
      }
    }
  ]
}
```
</details>

<details>
<summary>Configuration VSCode Workspace</summary>

```json
{
  "editor.formatOnSave": false,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "typescript.tsdk": "node_modules/typescript/lib"
}
```
</details>

```astro
---
const now = new Date()
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="viewport" content="width=device-width" />
    <meta name="generator" content={Astro.generator} />
    <title>Astro</title>
  </head>
  <body>
    <h1>Astro</h1>
    <pre>{now}</pre>
  </body>
</html>

```

### What did you expect to happen?

I'm used to https://github.com/antfu/eslint-config and like it a lot. Both linting and formatting is done with ESLint without Prettier. Is it possible to do the same with this plugin for Astro components? Everything is working as expected with the config above except for formatting the HTML template in Astro components. 

For example is the template below valid as of now. The tags and props don't have the correct indents and spacing.
```html
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <meta name ="viewport" content= "width=device-width" />
    <meta name="generator" content={Astro.generator} />
<meta name="description" content="Astro SSR with Vue" />
    <title>Astro</title>
  </head>
  <body>
    <h1>Astro</h1>
  </body>
</html>
```

These things would be fixed in Vue templates thanks to the rules from `esling-plugin-vue`. Is it possible to implement similar rules in this package? Like https://eslint.vuejs.org/rules/html-indent.html and https://eslint.vuejs.org/rules/no-multi-spaces.html.

The docs states that the plugin can "Apply a consistent code style to Astro components" but what does that mean? Are you supposed to use Prettier or have I configures the plugin incorrectly?

Thanks in advance!

### What actually happened?

Formatting is now working in the HTML template.

### Link to Minimal Reproducible Example

Not applicable.

**Comment by essarn** [comment]
Got formatting working for Astro HTML templates using the official Prettier plugin. It's not ideal but works good enough. Prettier is only enabled in Astro files and other Typescript ESLint settings from `@antfu` seems to work in the Frontmatter.

```json
{
  "semi": false,
  "singleQuote": true,
  "plugins": [
    "./node_modules/prettier-plugin-astro"
  ],
  "overrides": [
    {
      "files": "*.astro",
      "options": {
        "parser": "astro"
      }
    }
  ]
}
```
```json
{
  "extends": ["@antfu", "plugin:astro/recommended"],
  "plugins": ["prettier"],
  "overrides": [
    {
      "files": ["*.astro"],
      "parser": "astro-eslint-parser",
      "parserOptions": {
        "parser": "@typescript-eslint/parser",
        "extraFileExtensions": [".astro"]
      },
      "extends": ["prettier"],
      "rules": {
        "prettier/prettier": "error"
      }
    }
  ]
}
```
```json
{
  "editor.formatOnSave": false,
  "typescript.tsdk": "node_modules/typescript/lib",
  "[astro]": {
    "editor.formatOnSave": true
  }
}

```

Still the best case would be to format the HTML template using ESLint.

**Comment by ota-meshi** [comment]
This plugin has three stylistic rules. If there are other rules you want, please propose rules in the issue and send a PR to add the rules.

https://ota-meshi.github.io/eslint-plugin-astro/rules/#stylistic-issues

**Comment by ota-meshi** [comment]
The indent rules seem to work fine.

https://ota-meshi.github.io/eslint-plugin-astro/playground/#eJxtUN1OhTAMfpWlVxrlLHplCJCY+Bi7mazA4ujI6AFPCO9uxwnGC6/W76/tukEbHUIJRVEYaiPNrCiuqlaEq/qwjA+Phg7RUDXwGFSw1NcGkAw0mUPr8jsiW9UONs3IIl+5K94MKJ214OlLJQzCe5khNN8mzGi0Pep56Z++xyD0kLATWnd2ycaLKGePoz/ZMccWj+sUE4smLkbKE1fveKgdShKLA/wX7ZEwWY7pT3Z7nznFy6+032PsOWBzaJW+A2H1+eHP6G7HAV5Oj1SCp4TNJjfcK53LHDmtOh9QCniGdA04Q7mBJyc7QPm67z9k/Ymu

**Comment by essarn** [comment]
> The indent rules seem to work fine.
> 
> https://ota-meshi.github.io/eslint-plugin-astro/playground/#eJxtUN1OhTAMfpWlVxrlLHplCJCY+Bi7mazA4ujI6AFPCO9uxwnGC6/W76/tukEbHUIJRVEYaiPNrCiuqlaEq/qwjA+Phg7RUDXwGFSw1NcGkAw0mUPr8jsiW9UONs3IIl+5K94MKJ214OlLJQzCe5khNN8mzGi0Pep56Z++xyD0kLATWnd2ycaLKGePoz/ZMccWj+sUE4smLkbKE1fveKgdShKLA/wX7ZEwWY7pT3Z7nznFy6+032PsOWBzaJW+A2H1+eHP6G7HAV5Oj1SCp4TNJjfcK53LHDmtOh9QCniGdA04Q7mBJyc7QPm67z9k/Ymu

That's weird none of the `Layout & Formatting` rules seems to work for me in the HTML template. Are they enabled by default or do I have to do something?

**Comment by essarn** [comment]
Hi again @ota-meshi
The format rules still doesn't work with the plugin maybe I'm doing something wrong? Do you have any guess as to why it doesn't work?

**Comment by essarn** [comment]
> > The indent rules seem to work fine.
> > https://ota-meshi.github.io/eslint-plugin-astro/playground/#eJxtUN1OhTAMfpWlVxrlLHplCJCY+Bi7mazA4ujI6AFPCO9uxwnGC6/W76/tukEbHUIJRVEYaiPNrCiuqlaEq/qwjA+Phg7RUDXwGFSw1NcGkAw0mUPr8jsiW9UONs3IIl+5K94MKJ214OlLJQzCe5khNN8mzGi0Pep56Z++xyD0kLATWnd2ycaLKGePoz/ZMccWj+sUE4smLkbKE1fveKgdShKLA/wX7ZEwWY7pT3Z7nznFy6+032PsOWBzaJW+A2H1+eHP6G7HAV5Oj1SCp4TNJjfcK53LHDmtOh9QCniGdA04Q7mBJyc7QPm67z9k/Ymu
> 
> That's weird none of the `Layout & Formatting` rules seems to work for me in the HTML template. Are they enabled by default or do I have to do something?

Really need some help on this @ota-meshi 
Why is the formatting not working for me like you showed in the playground?

**Comment by ota-meshi** [comment]
You didn't share the repository. I can't help you.
