### ISSUE TITLE
rule "label-has-associated-control" from plugin:astro/jsx-a11y uses react htmlFor instead for

### ISSUE THREAD

**Issue by xididri** [ota-meshi/eslint-plugin-astro#123]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

v7.32.0

### What version of `eslint-plugin-astro` are you using?

eslint-plugin-astro

### What did you do?

<details>
<summary>Configuration</summary>

```js
module.exports = {
	env: {
		browser: true,
		es2021: true,
		node: true,
	},
	parserOptions: {
		ecmaVersion: 11,
		sourceType: 'module',
	},
	extends: [
		'plugin:astro/recommended',
		'plugin:astro/jsx-a11y-recommended',
	],
	overrides: [
		{
			files: ['*.astro'],
			parser: 'astro-eslint-parser',
			parserOptions: {
				parser: '@typescript-eslint/parser',
				extraFileExtensions: ['.astro'],
			},
			rules: {
				// allows to declare Astro components props without warning from rule no-unused-vars
				'no-unused-vars': ['warn', { varsIgnorePattern: 'Props' }], 
			},
		},
	],
}
```
</details>

```astro
<form>
	<label class="label" for="address">Address</label>
	<textarea placeholder="Address" required name="address" id="address"></textarea>
	<input type="submit" value="Submit">
</form>
```

### What did you expect to happen?

No errors from ESLint

### What actually happened?

ESLint complains that `htmlFor` attribute is not defined on labels.

### Link to Minimal Reproducible Example

https://github.com/xididri/astro-eslint-jsx-a11y

### Additional comments

In React components we must use `htmlFor` instead of `for` since it is a reserved keyword (same reason why `className` is used instead of `class`. Resulting HTML has `for`.

In Astro there is no such a thing, therefore the rule should be adapted to check for `for` attribute instead of `htmlFor`.

**Comment by xididri** [comment]
Forgot to include the error message:

```
error  A form label must be associated with a control  astro/jsx-a11y/label-has-associated-control
```

**Comment by ota-meshi** [comment]
Thank you for reporting the issue!
I will fix it.

**Comment by xididri** [comment]
Wow that was quick! Thank you so much ;-)

However I upgraded to latest version 0.21.0 (from the [changelog](https://github.com/ota-meshi/eslint-plugin-astro/releases) 0.20.1 includes the fix) and the issue is gone!
