### ISSUE TITLE
Parsing error within <script>

### ISSUE THREAD

**Issue by valentinbeggi** [ota-meshi/eslint-plugin-astro#132]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

9.27.0

### What version of `eslint-plugin-astro` are you using?

0.21.0

### What did you do?

I got parsing errors on Typescript as keyword while trying to cast a type within a <script> tag.
Since I'm extending 'plugin:astro/recommended' I believe the prettier/prettier rule is turned off so it's not really the same as #95 right ?

Here's a screenshot of the error

<img width="895" alt="Capture d’écran 2022-11-07 à 23 01 24" src="https://user-images.githubusercontent.com/87306219/200424659-65429a09-70af-4cc6-a35a-d96f8186d7aa.png">

<summary>Configuration</summary>

```
module.exports = {
  plugins: ['import', 'tailwindcss'],
  extends: [
    'eslint:recommended',
    'plugin:astro/recommended',
    'plugin:import/recommended',
    'plugin:prettier/recommended',
    'plugin:tailwindcss/recommended',
  ],
  rules: {
    'import/no-unresolved': 0,
    'import/order': [
      'error',
      {
        groups: [
          ['external', 'builtin'],
          'unknown',
          'internal',
          ['parent', 'sibling', 'index'],
        ],
        alphabetize: {
          order: 'asc',
          caseInsensitive: false,
        },
        'newlines-between': 'always',
        pathGroupsExcludedImportTypes: ['builtin'],
      },
    ],
    'sort-imports': [
      'error',
      {
        ignoreCase: true,
        ignoreDeclarationSort: true,
        ignoreMemberSort: false,
        memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
      },
    ],
    'tailwindcss/no-custom-classname': 'off',
    'tailwindcss/no-contradicting-classname': 'warn',
  },
  overrides: [
    {
      files: ['*.astro'],
      parser: 'astro-eslint-parser',
      parserOptions: {
        parser: '@typescript-eslint/parser',
        extraFileExtensions: ['.astro'],
      },
    },
  ],
  env: {
    node: true,
  },
};

```
</details>

```astro
---
import { Icon } from 'astro-icon';

import Delimiter from './Delimiter.astro';
---

<script>
  const header = document.getElementById('navheader') as HTMLElement;
  const menuBtn = document.getElementById('menubtn') as HTMLElement;
  const logo = document.getElementById('navlogo') as HTMLElement;

  menuBtn.onclick = () => header.classList.toggle('open');

  if (matchMedia('(pointer:fine)').matches) {
    logo.addEventListener('contextmenu', event => {
      event.preventDefault();
      window.location.href = '/press';
    });
  }
</script>
```

Thanks in advance for your help !

### What did you expect to happen?

No parsing error

### What actually happened?

Parsing error: Unexpected token as (eslint)

### Link to Minimal Reproducible Example

-

**Comment by valentinbeggi** [comment]
Hey,
I created a minimal example where the error occurs, please tell me if you need more
https://github.com/valentinbeggi/repro-astro-parser-error

**Comment by ota-meshi** [comment]
Add the following to the overrides section of your eslint configuration.

```js
  overrides: [
    // ...
    {
      // Define the configuration for `<script>` tag.
      // Script in `<script>` is assigned a virtual file name with the `.js` extension.
      files: ['**/*.astro/*.js', '*.astro/*.js'],
      parser: '@typescript-eslint/parser',
      rules: {
        'prettier/prettier': 'off',
      },
    },
  ],
```

**Comment by smnbbrv** [comment]
Just faced this issue, very confusing... Is this going to be added somehow to the README?

**Comment by ota-meshi** [comment]
Welcome PR. Could you add it to the FAQ section?
https://ota-meshi.github.io/eslint-plugin-astro/user-guide/#-faq

**Comment by JulianCataldo** [comment]
Was facing this issue too.
Interesting solution.
In fact, auto-import leaks the sub JS file in astro (like `*.astro.ts/script_*.js`) file, in the client part.

Thanks a lot for your hard work! It's very useful.

**Comment by XiNiHa** [comment]
I guess this should be fixed on Astro's side (or at least allow something like `lang="ts"` on `<script>`) to make the inline script have `.ts` extension 🤔 Completely disabling `prettier/prettier` on inline scripts doesn't make sense to me.

**Comment by smnbbrv** [comment]
@ota-meshi actually facing the same issue now after upgrading to eslint v9 and failing to understand how to configure this properly.

Neither this

```js
  {
    ignores: ['**/*.astro/*.js', '*.astro/*.js'],
    ...prettierRecommended,
  },
```

nor

```js
  ...prettierRecommended,
  {
    // Define the configuration for `<script>` tag.
    // Script in `<script>` is assigned a virtual file name with the `.js` extension.
    files: ['**/*.astro/*.js', '*.astro/*.js'],
    parser: tsParser,
    rules: {
      'prettier/prettier': 'off',
    },
  },
```

work any longer. Do you know a way to resolve this in v9?
