### ISSUE TITLE
Question about JSX like element definitions

### ISSUE THREAD

**Issue by high1** [ota-meshi/eslint-plugin-astro#133]
I'm using @typescript-eslint to parse Astro components, and I'm getting this error when using dynamic JSX expressions:
![image](https://user-images.githubusercontent.com/783303/202390264-724bb785-70fc-4705-9616-c251ab8a23cd.png)
I suppose that this is caused by missing definitions for JSX like elements in astro? Is there a way to reference the definitions in Astro? I can fix this using type assertions with HTMLAnchorELement, but it would be better if the definitions were already inferred...

env.d.ts references these types
```
/// <reference types="astro/client" />
/// <reference types="astro/env" />
/// <reference types="svelte" />
```

Thanks for this plugin, btw, and all the other ones - I'm using quite a few of them...

**Comment by ota-meshi** [comment]
I'm not familiar with typescript so I'm not sure. Could you share your repository for me to debug?

**Comment by high1** [comment]
I'll make a repro as soon as I can.

**Comment by high1** [comment]
Tried to reproduce the issue on a fresh project, with the same configuration - started with the new astro starter, and haven't been able to.
![image](https://user-images.githubusercontent.com/783303/202639407-3b77a86f-7b0b-49b7-932a-bdc5a5fd8401.png)
I'm closing the issue since I can't repeat it consistently.
