### ISSUE TITLE
Request: built-in config for astro.config.mjs

### ISSUE THREAD

**Issue by jamesarosen** [ota-meshi/eslint-plugin-astro#166]
### Description

This plugin defines great overrides for `.astro` files! It would be nice if it did the same for other Astro-specific files like `astro.config.mjs`.

Here's my first attempt:
```js
{
  files: ['astro.config.mjs'],
  env: {
    node: true,
    'astro/astro': true, // I'm not sure about this
    es2020: true,
  },
  parserOptions: {
    sourceType: 'module',
  },
},
```

**Comment by ota-meshi** [comment]
Thank you for posting the issue.

Since this plugin is focused on `*.astro` files, I don't want to provide that.
You can publish your shareable configuration and provide it to people.
