### ISSUE TITLE
Parsing error: Expression expected on .astro files frontmatter

### ISSUE THREAD

**Issue by pedro199288** [ota-meshi/eslint-plugin-astro#175]
I'm not opening this as a bug as I'm not sure if it is. My problem is that eslint shows an error at the top of my `.astro` files in the frontmatter, like this (because of the three dashes):

![image](https://user-images.githubusercontent.com/40956528/223652600-df344280-7bfe-44f7-a24a-c05e82f39273.png)

Is this expected or maybe I'm missing something in the configuration?

this is my eslint config (I have also tested with only `'plugin:astro/recommended' `in the `extends` property and is the same):
```js
module.exports = {
  extends: ['semistandard', 'plugin:astro/recommended', '../.eslintrc.js'],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    project: './tsconfig.json',
    extraFileExtensions: ['.astro']
  },
  override: [
    {
      files: ['*.astro'],
      parser: 'astro-eslint-parser',
      parserOptions: {
        parser: '@typescript-eslint/parser',
        extraFileExtensions: ['.astro']
      },
      rules: {
        // override/add rules settings here, such as:
        // 'astro/no-set-html-directive': 'error'
      }
    }
  ]
};
```

This is my astro version:
    "astro": "^2.1.0",

and this is my eslint dependencies:
    "astro-eslint-parser": "^0.11.0",
    "eslint": "^8.35.0",
    "eslint-plugin-astro": "^0.23.0",

**Comment by ota-meshi** [comment]
> Is this expected or maybe I'm missing something in the configuration?

You provided too little information and I don't know what your configuration is missing.

**Comment by pedro199288** [comment]
Looks like the issue was not related to the plugin itself but to how the eslint config was being loaded (the one with eslint astro plugin wasn't loading correctly). Sorry and thanks for your time! I'll close the issue

**Comment by marekbrze** [comment]
@pedro199288 what did you change? I have the same error.

**Comment by pedro199288** [comment]
> @pedro199288 what did you change? I have the same error.

It was due to a bad configuration on my eslint file (maybe a not needed comma or something like that). You can check the "output" tab in vscode to see if some error is shown so you can fix it :)

**Comment by marekbrze** [comment]
I messed config filed, but now it's working 👌Thanks for the response!

**Comment by abdulhadiayaz** [comment]
@marekbrze how did you fixed, i am facing same error

**Comment by marekbrze** [comment]
Unfortunately I don't remember after 2 years... but probably something with the structure of the config file

**Comment by Wexcode** [comment]
Order matters in the eslint config file. I ran into this issue when I put `...eslintPluginAstro.configs.recommended,` as the first entry of the configuration, but was able to resolve this by following the recommended ordering in the documentation:
```
  // add more generic rule sets here, such as:
  // js.configs.recommended,
  ...eslintPluginAstro.configs.recommended,
```

**Comment by enihsyou** [comment]
In my case, the order matters. Put typescript-eslint in front of eslint-plugin-astro fix this error for me.

```diff
import { defineConfig } from "eslint/config";
import astro from "eslint-plugin-astro";
import tseslint from "typescript-eslint";

export default defineConfig([
-    ...astro.configs.recommended,
-    ...tseslint.configs.recommended,
+    ...tseslint.configs.recommended,
+    ...astro.configs.recommended,
]);
```

**Comment by DerTimonius** [comment]
@enihsyou you just saved my sanity, thank you!

@ota-meshi might be a good idea to add a quick note to the docs that state that the order is important?
