### ISSUE TITLE
Rule for single quote

### ISSUE THREAD

**Issue by erupturatis** [ota-meshi/eslint-plugin-astro#193]
### Motivation

I am not sure if you can do it with a workaround plugin, but it isn't a rule natively in the plugin as far as I know

### Description

When I write class = "..." to throw an error to change to single quotes

### Examples

```astro
---
---

{/* ✓ GOOD */}
<div class = 'cls' />

{/* ✗ BAD */}
<div class ="cls" />
```

### Additional comments

thats all

**Comment by ota-meshi** [comment]
Hi @erupturatis.

I think you can use jsx-quotes rule.

https://eslint.org/docs/latest/rules/jsx-quotes

```astro
---
/* eslint jsx-quotes: ['error', 'prefer-single'] */
---

{/* ✓ GOOD */}
<div class = 'cls' />

{/* ✗ BAD */}
<div class ="cls" />
```

[DEMO](https://ota-meshi.github.io/eslint-plugin-astro/playground/#eJxtyzEKAjEQQNGrDNMElg3bBxUUwXIPYCwkO0okTNzMrgghp7Cw8XSexGBjY/t5P6OLA6FBrbXlrgGS4HmCi9z1OMeJxMBeUUoxqRbUNdGJkhbP50DqAE1n+XtaznV+vx6w6/tt7cXyYvA3cOEoAktQLoiCbvWjT9is/0iLVVqsFFtMcyBBk0v5AEBANvI=)

**Comment by erupturatis** [comment]
Thank you
