### ISSUE TITLE
Attempts to validate JSON script tags

### ISSUE THREAD

**Issue by SudoCat** [ota-meshi/eslint-plugin-astro#210]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.41.0

### What version of `eslint-plugin-astro` are you using?

0.27.0

### What did you do?

<details>
<summary>Configuration</summary>

Base (custom)
```
module.exports = {
  env: {
    browser: true,
    es2022: true,
    node: true,
    "jest/globals": true,
  },
  globals: {
    NodeListOf: "readonly",
  },
  extends: [
    "eslint:recommended",
    "plugin:import/recommended",
    "turbo",
    "prettier",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaVersion: "latest",
    sourceType: "module",
  },
  plugins: ["react", "@typescript-eslint"],
  overrides: [
    {
      // Only test react against jsx/tsx files
      files: ["*.jsx", "*.tsx"],
      extends: ["plugin:react/recommended", "plugin:react-hooks/recommended"],
    },
    {
      files: ["*.ts", ".tsx"],
      extends: [
        "plugin:@typescript-eslint/recommended",
        "plugin:import/typescript",
      ],
    },
    {
      files: ["*.test.*"],
      plugins: ["jest"],
      extends: ["plugin:jest/recommended"],
      rules: {
        // suppress errors for missing 'import React' in files
        "react/react-in-jsx-scope": "off",
      },
    },
  ],
  rules: {
    "import/order": ["error"],
    // eslint-import does not support package.json#exports
    // https://github.com/import-js/eslint-plugin-import/issues/2132
    "import/no-unresolved": [0],
    // allow jsx syntax only in [tj]sx files
    "react/jsx-filename-extension": [
      1,
      { extensions: [".tsx", ".jsx", ".astro"] },
    ],
  },
  settings: {
    react: {
      version: "^18.0.0",
    },
  },
};

```

Astro
```
module.exports = {
  root: true,
  extends: ["plugin:astro/recommended", "custom"],
  overrides: [
    {
      // Define the configuration for `.astro` file.
      files: ["*.astro"],
      // Allows Astro components to be parsed.
      parser: "astro-eslint-parser",
      // Parse the script in `.astro` as TypeScript by adding the following configuration.
      // It's the setting you need when using TypeScript.
      parserOptions: {
        parser: "@typescript-eslint/parser",
        extraFileExtensions: [".astro"],
      },
    },
  ],
};

```
</details>

```astro
<script type="application/ld+json">
{
  "@context": "http://www.schema.org",
  "@type": "Organization",
  name: "Example"
}
</script>
```

### What did you expect to happen?

eslint-plugin-astro should ignore script tags with `*json` or `importmap` as the type parameter.

### What actually happened?

> `Parsing error: ';' expected.`

### Link to Minimal Reproducible Example

https://ota-meshi.github.io/eslint-plugin-astro/playground/#eJwlzDEOgCAQBMCvkG0t6I3ykm0Qr4DgcVEKjfHvmlhOMzdSWwUjpiPt2brrl8lMRLOaU+y5qa/rUI6mRKDeVOcIOeNmVYjxQ1uKpE5QH+rk/yjgeQHd9CBL

**Comment by ota-meshi** [comment]
Thank you for posting the issue.
It seems that in some condition we need to exclude the script fragment returned by the processor.
https://github.com/ota-meshi/eslint-plugin-astro/blob/541a9baa63fb87c138c081cf37a1e320ea45661a/src/processor/index.ts#L20-L26
If you want it fixed sooner, please consider opening a PR.

**Comment by SudoCat** [comment]
Thanks for pointing me in the right direction! I was just trying to find where to make the change. PR created and fix ready to go.

Oh and a big thank you for creating this plugin in the first place, it's a huge help! 🎉
