### ISSUE TITLE
Support for Flat Config

### ISSUE THREAD

**Issue by JosefJezek** [ota-meshi/eslint-plugin-astro#241]
### Description

- https://eslint.org/docs/latest/use/configure/configuration-files-new
- https://eslint.org/docs/latest/use/configure/migration-guide#start-using-flat-config-files

**Comment by ota-meshi** [comment]
I welcome pull requests

**Comment by Sergih28** [comment]
I'd be happy to see this issue move forward :smiley: 

I'm a react dev, so I guess I could help if given some guidance, as I don't know how this project works :grimacing:

**Comment by darvid** [comment]
I managed to get it working, not sure if this is the best way to do it, though... here's the relevant portion of my `.eslint.config.js`:

```js
// ... other eslint parsers/plugins ...
import ts from "@typescript-eslint/eslint-plugin";
import astroParser from "astro-eslint-parser";
import astro from "eslint-plugin-astro";

export default [
  // ...
  {
    files: ["**/*.astro"],
    plugins: {
      astro,
    },
    languageOptions: {
      globals: {
        // Enables global variables available in Astro components.
        node: true,
        "astro/astro": true,
        es2020: true,
      },
      parser: astroParser,
      parserOptions: {
        parser: "@typescript-eslint/parser",
        extraFileExtensions: [".astro"],
        // The script of Astro components uses ESM.
        sourceType: "module",
      },
    },
    rules: {
      ...astro.configs.all.rules,
    },
  },
  {
    // Define the configuration for `<script>` tag.
    // Script in `<script>` is assigned a virtual file name with the `.js` extension.
    files: ["**/*.astro/*.js", "*.astro/*.js"],
    languageOptions: {
      globals: {
        browser: true,
        es2020: true,
      },
    },
    parserOptions: {
      sourceType: "module",
    },
    rules: {
      // override/add rules settings here, such as:
      // "no-unused-vars": "error"

      // If you are using "prettier/prettier" rule,
      // you don't need to format inside <script> as it will be formatted as a `.astro` file.
      "prettier/prettier": "off",
    },
  },
  {
    // Define the configuration for `<script>` tag when using `client-side-ts` processor.
    // Script in `<script>` is assigned a virtual file name with the `.js` extension.
    files: ["**/*.astro/*.ts", "*.astro/*.ts"],
    languageOptions: {
      globals: {
        browser: true,
        es2020: true,
      },
    },
    parser: tsParser,
    parserOptions: {
      sourceType: "module",
      project: null,
    },
    rules: {
      // override/add rules settings here, such as:
      // "no-unused-vars": "error"

      // If you are using "prettier/prettier" rule,
      // you don't need to format inside <script> as it will be formatted as a `.astro` file.
      "prettier/prettier": "off",
    },
  },
];
```

ℹ️ the individual flat configuration are mostly copied wholesale from the [user guide](https://ota-meshi.github.io/eslint-plugin-astro/user-guide/#configuration), with small tweaks to use the imported plugin and parser(s) - I'm sure the shareable configuration is possible, but I'm going with non-shareable.

**Comment by TheElegantCoding** [comment]
sometimes i get this error with that implementation 
![image](https://github.com/ota-meshi/eslint-plugin-astro/assets/70770072/c132fb5f-6491-4e5b-9191-c77d604c9c1b)

**Comment by darvid** [comment]
@TheElegantCoding hmm, even with `files` set to `["**/*.astro"]`? I would perhaps run ``eslint --debug src/`` and see if it matches files?

**Comment by TheElegantCoding** [comment]
my mistake was that i dont put `["**/*.astro"]` thanks

**Comment by raulfdm** [comment]
Although the workaround works in some versions, using the new package from typescript eslint doesn't seem to work properly: https://typescript-eslint.io/packages/typescript-eslint. 

It seems there's a mismatch between the TS code being evaluated vs the old typescript of astro eslint plugin while linting

**Comment by TheElegantCoding** [comment]
Really thank you @ota-meshi, I will see the flat config support when I have time
