### ISSUE TITLE
Parsing error: Declaration or statement expected. ESLint(FATAL)

### ISSUE THREAD

**Issue by FDiskas** [ota-meshi/eslint-plugin-astro#265]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.50.0

### What version of `eslint-plugin-astro` are you using?

0.29.1

### What did you do?

My goal was to remove white space from the icon and a component. So I used `<!-- WHITESPACE -->` HTML comment hack.
But in this case, I get a parsing error at a random location
![image](https://github.com/ota-meshi/eslint-plugin-astro/assets/468006/c1ac993d-a3f3-4246-b12f-37d770fc0dc4)

```astro
---
import { Sprite } from 'astro-icon';
import CategoryNavItem from '@components/menu/CategoryNavItem.astro';
import type { CategoryLinkItem } from 'src/const/links.ts';

interface Props {
  items: CategoryLinkItem[];
  class?: string;
  id?: string | number;
}

const { items, class: className = 'pl-0', id = '' } = Astro.props;
---

<!-- CategoryNav -->
<ul class="list-none" class:list={[className]}>
  {
    items.map((item) => (
      <li class="overflow-hidden truncate">
        {item.children != null ? (
          <label class="text-black dark:text-white">
            <input type="radio" name={`categoryList-${id}`} class="peer hidden" />
            <Sprite
              name="arrow"
              class="w-24 h-24 inline cursor-pointer -rotate-90 peer-checked:rotate-0 peer-checked:text-red"
            /><!--
             --><CategoryNavItem item={item} class="peer-checked:text-red" />
            <Astro.self items={item.children} class="pl-24 hidden basis-full peer-checked:block" id={item.id} />
          </label>
        ) : (
          <CategoryNavItem item={item} class="pl-24 text-black dark:text-white" />
        )}
      </li>
    ))
  }
</ul>
```

### What did you expect to happen?

It should allow me to write the wrong HTML syntax or use an HTML comment hack

### What actually happened?

It displays
```
Parsing error: Declaration or statement expected.ESLint(FATAL)
```
at the random file location if I use HTML comment

### Link to Minimal Reproducible Example

Repository: https://github.com/FDiskas/eslint-plugin-astro-parsing-error

Possible reproduction 
https://ota-meshi.github.io/eslint-plugin-astro/playground/#eJyFVctu3DgQ/BWtjkEIIbs3Y3ZuC+QP9jIXimpJXLdILh/2KIb/PUVqRo+JjRwMu6vLzX5Ut95qZTuqn2ohxMU0X6p/iZWdqIq2osDaROE4DdoIGaK31ZfmYgr1JH3Uiul8MVV1Gr9VimUIf1/qSNco/rrypT6/RR2Z3k/N+G2hufN3Yranxi22Ni7F43+2LNVz1Un//FTs11FHutSZXlXN+fRHfvwf762vvpOnjAtxvkWKsyME8rLT9lKvgR2Rr0bddWSANsvbDcuWGH+fmq2U+mvtE1Oon97qUnBjrAgUxRgnFp32pKJ+Qb/+/Hr0l1w/8SeTAnVChQAqg2H9juA89eRFyVWwDh+HubFs+x9cO/KvlOBYf8IINOliKmsApJyJCMnRkk8P6/a2NQUZKEaE9BSTXxCUI8NslHDeTjqQoCupdK8IXiUBdoT3vcxxwuooGeFHD2soKM1JT8LQIH6Qtxtuul+oSPkjTEKima/XrBcPCmZkPtD1DnbUpmEgv9lMkcSL3BD0Qkg/hAOwZD7R1JI/eohRrO4P2DPNexJrJfFIbssdpcnF+WAINaJdKt51cHQ6maew1kbXhzZAel6K1lomafJL8ehZxw6kl8xx9DYN4woljPMYcWDbSn4A9eSsfxyBNi+Sdbc02q2oh50ggWV9g5NqrZ4tmml7CIiUDruZQU4ooNNm+Kwdk75ij0o0KAkSibJdnYZeRZin1vKKWGNVRB2Qo57wm4KSbk0Eu4RmMa8RCvluQN/R5nsi2qQ56k3InhZ50wag9ltadwyL3j+0Kny0TGGUnX0FiH3UqLgTRk67MFiPkCXp5aaqOOogWsK60m57y6HpqN8MDIRKyCmhANxy2nyeJJrc8g4KsifRa4OWzA8o9lPu1+sGW5dBNBahtMHgNn+5eOXChgcQ67ZB+R5CDi1ufrleZDah3J3YHzU+gsdRvuq4MDz9n3DBxKyJu4KkvKHByCX3Rax5rLY/HmlcjB67Gss1Xy9wOJI6yqqVuacFQ24QGTack+ffUHtCGfkukYm/oUINlh+/IjsWzjKC+LmdA77NH35sIATMuzQbOypCnHkfb+lDPr+64O/vPwEdnsRa

### Additional comments

Thank you ❤️ for any advice or fix

**Comment by ota-meshi** [comment]
The solution for now is to remove the useless `</label>`. `@astrojs/compiler` does not return a lone `</label>` as an AST, so it cannot parse it well.

**Comment by FDiskas** [comment]
I have a case where is no useless elements and still got such a problem . example in description

**Comment by ota-meshi** [comment]
I can't reproduce the parsing error. It might be a problem with prettier.

https://ota-meshi.github.io/eslint-plugin-astro/playground/#eJyNVF1r2zAU/Su3ZpAGqriMvcyN3Y09DUYZ7LEuVJGURkSWjCQ3K57/+64kx03cMvYSx/fjnHPvPUmfMcNFVmSEkFrLpjXWQw+/Wiu9gAG21jSwoM5bQyQzenEzVX2jXjwZ+3JHn7970YylX5jBtBbau7wRustnZauIdQLjX1qBjMeyH1LvI9yR21mWI7HzucKUW3kXmrFde2G3lAn4aU3roK81AIpuXPEG7P7hJmSZos7dFoAKpH6KIcmnd/gDums2wmJiCAyRFaVF0KvUXaTHHW0ElLBoFbleXCFKeFmg5hK+hvlWbdCEQHGttV5fEHK6MCCkwminElxZZ0o6TzQurs5GphAp+/uJ72GoguI45zjpqqHt5WX4uoSygsuUAlgrOQGbZ1yTMgeyk5wLDd52mqGSOquO5QgaMFZsJxW3WHNR4iqUgttXyARLN+JVshe/PdkoyvbAqd0X8f2wkzPs2Cl126VbY6OlXBqcU+NUZf/IpmvhCj70kg+Pw0TSCmEhSceOfI6bjHoehARcZ9Rac6izefYIfSAfP8EufEiN3hLAOuuMJa2J3gJijUdp5PM1BBWE7QTbC16M4Vk0Tm8Fn/PlVTj+TAOefz3//YQTlPEQ59O/w/B2D8l1TqhtckZ5ftETRBWnTl7YUCcd2YZTnzFtlGF7pJF8xMGbzDjXeTTDSWwJxcwu/zVh1PMvK50RL4fJ4/h/MCaWy/DEzDrvVJUNfwFOpY5e
