### ISSUE TITLE
Docs site renders : book : instead of :book:

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [ota-meshi/eslint-plugin-astro#289]
On https://ota-meshi.github.io/eslint-plugin-astro/user-guide, exactly one heading has `:book:` (raw GFM) instead of a rendered emoji:

![Screenshot of ":book: Usage" in a rendered heading](https://github.com/ota-meshi/eslint-plugin-astro/assets/3335181/0c5d6b4a-c63c-4934-bee8-d7fb945e814f)

Is there an alias for the emoji that should be used instead, maybe?

**Comment by ota-meshi** [comment]
Thank you for letting me know :smile: 
I'm using `remark-emoji` to replace emojis, but only `:book:` doesn't seem to work on our site.
I think it's better to replace them with raw emojis than to investigate the cause, so I'll do that.
