### ISSUE TITLE
Parsing error (',' expected) in <script> with typescript

### ISSUE THREAD

**Issue by Garmelon** [ota-meshi/eslint-plugin-astro#291]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.55.0

### What version of `eslint-plugin-astro` are you using?

0.30.0

### What did you do?

<details>
<summary>Configuration</summary>

`.eslintrc.json` contents:
```json
{
    "env": {
        "browser": true,
        "es2021": true,
        "node": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:astro/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": "latest",
        "sourceType": "module"
    },
    "plugins": [
        "@typescript-eslint"
    ],
    "rules": {
    },
    "overrides": [
        {
            "files": ["*.astro"],
            "parser": "astro-eslint-parser",
            "parserOptions": {
                "parser": "@typescript-eslint/parser",
                "extraFileExtensions": [".astro"]
            },
            "rules": {
            }
        }
    ]
}
```

`package.json` contents:
```json
{
  "name": "radiant-raspberry",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro check && astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/check": "^0.3.2",
    "astro": "^4.0.4",
    "typescript": "^5.3.3"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^6.14.0",
    "@typescript-eslint/parser": "^6.14.0",
    "eslint": "^8.55.0",
    "eslint-plugin-astro": "^0.30.0"
  }
}
```
</details>

When running `npx eslint .` on an astro project using typescript and containing a script block like below, eslint reports `Parsing error: ',' expected`. This does **not** happen if the code is instead placed in the component script.

```astro
<script>
	const x = new Map<string, string>();
</script>
```

### What did you expect to happen?

There should be no parsing error, only errors caused by lints.

### What actually happened?

```
❯ npx eslint .

/home/garmelon/tmp/radiant-raspberry/src/pages/index.astro
  19:33  error  Parsing error: ',' expected

✖ 1 problem (1 error, 0 warnings)
```

### Link to Minimal Reproducible Example

https://github.com/Garmelon/astro-eslint-bug-repro

**Comment by ota-meshi** [comment]
Thank you for posting this issue.
That's a bug. I would like to find a way to fix it.

**Comment by ota-meshi** [comment]
I added the `astro/client-side-ts` processor to work around the problem. Use it like this:

```js
  overrides: [
    {
      files: ["*.astro"],
      // ...
      processor: "astro/client-side-ts", // <- Uses the "client-side-ts" processor.
      rules: {
        // ...
      },
    },
    // ...
  ],
```

**Comment by Garmelon** [comment]
Thanks! Can confirm that this fixes the error.

**Comment by davidhouweling** [comment]
Hi @ota-meshi / @Garmelon, when I attempt to add the processor I'm getting the following issue when i attempt to run eslint
```
Error: ESLint configuration of processor in '.eslintrc.cjs#overrides[0]' is invalid: 'astro/client-side-ts' was not found.
```

These are my package.json dependencies (stripped to what is relevant)
```
  "dependencies": {
    "astro": "^4.0.6",
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^6.14.0",
    "@typescript-eslint/parser": "^6.14.0",
    "eslint": "^8.56.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-astro": "^0.29.1",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-jsx-a11y": "^6.8.0",
    "eslint-plugin-prettier": "^5.0.1",
    "prettier": "^3.1.1",
    "prettier-plugin-astro": "^0.12.2",
    "typescript": "^5.3.3"
```

**Comment by Garmelon** [comment]
This fix requires version `0.31.0` of `eslint-plugin-astro`.

**Comment by davidhouweling** [comment]
thanks, i forced the update. I thought I had done it properly last night.

**Comment by davidhouweling** [comment]
Just following up from this @Garmelon, in VSCode it is working fine... however when i run `eslint . --ext .js,.ts,.astro` it is still failing on the typescript parsing issues

**Comment by Garmelon** [comment]
If you're running eslint globally instead of via `npx` or similar, maybe you have an outdated version of `eslint-plugin-astro` installed globally as well

**Comment by davidhouweling** [comment]
checked both my npm and yarn globals and there is no eslint-plugin-astro installed. Also i set up this inside the `scripts` section of package.json file as `lint` and did a `npm run lint` and it has the issue.

**Comment by Garmelon** [comment]
Maybe open another issue with a minimal reproducible example then.
