### ISSUE TITLE
Missing lint errors on <script>

### ISSUE THREAD

**Issue by erikschul** [ota-meshi/eslint-plugin-astro#308]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

v8.56.0

### What version of `eslint-plugin-astro` are you using?

0.31.3

### What did you do?

See "TODOBROKEN" text in the linked MRE, which are supposed to trigger lint errors.

### What did you expect to happen?

Lint errors

### What actually happened?

No lint errors

### Link to Minimal Reproducible Example

https://github.com/erikschul/astro-base

### Additional comments

See README.md for details.

I appreciate any help on this.

I suspect it may be a configuration issue with `.eslintrc.cjs` and `tsconfig.json`.

It seems that when I modify `<script>`, it creates a `.tsx` file (which is noticable in `npx astro dev`) but then quickly deletes it. I don't see any files in `.astro`, but the recommended `overrides` suggests that there would be. Can you provide any information relating to this?

**Comment by ota-meshi** [comment]
I don't really understand. What is TODOBROKEN? Please explain in detail in this issue.

**Comment by ota-meshi** [comment]
I checked your repository and it seems to contain various questions. I can't fully support you, so please divide the problem into parts and share them one by one.

**Comment by erikschul** [comment]
@ota-meshi I was just wondering if there's a way to lint/compile check the code without doing a build, i.e. check for type and lint errors. `TODOBROKEN` was just an attempt to write arbitrary invalid code.
