### ISSUE TITLE
Error when I use Chinese

### ISSUE THREAD

**Issue by GreedyWhale** [ota-meshi/eslint-plugin-astro#311]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.56.0

### What version of `eslint-plugin-astro` are you using?

0.31.3

### What did you do?

```
---
interface Props {
  title: string;
}

const { title } = Astro.props;
const metaInfo = {
  title: '测试',
  description: '一个前端工程师的技术笔记',
  keywords: '技术笔记, 前端开发, 编程教程, Web 开发, 前端工具'
};
---
---
interface Props {
  title: string;
}

const { title } = Astro.props;
const metaInfo = {
  title: '测试',
  description: '一个前端工程师的技术笔记',
  keywords: '技术笔记, 前端开发, 编程教程, Web 开发, 前端工具'
};
---

<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="title" content={metaInfo.title} />
    <meta name="description" content={metaInfo.description} />
    <meta name="keywords" content={metaInfo.keywords} />
    <meta name="robots" content="index, follow" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="language" content="Chinese" />
    <meta name="revisit-after" content="1 days" />
    <meta name="author" content="Caisr" />

    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, minimal-ui" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="generator" content={Astro.generator} />
    <title>{title}</title>
  </head>
  <body>
    <slot />
  </body>
</html>
<style is:global>
  :root {
    --accent: 136, 58, 234;
    --accent-light: 224, 204, 250;
    --accent-dark: 49, 10, 101;
    --accent-gradient: linear-gradient(
      45deg,
      rgb(var(--accent)),
      rgb(var(--accent-light)) 30%,
      white 60%
    );
  }
  html {
    font-family: system-ui, sans-serif;
    background: #13151a;
    background-size: 224px;
  }
  code {
    font-family:
      Menlo,
      Monaco,
      Lucida Console,
      Liberation Mono,
      DejaVu Sans Mono,
      Bitstream Vera Sans Mono,
      Courier New,
      monospace;
  }
</style>
```

### What did you expect to happen?

Perform eslint checks normally

### What actually happened?

When my Chinese characters reach a certain number, eslint reports an error。

```
Parsing error: Unknown token at 1016, expected: "is:global", actual: "<slot />\n "
```

### Link to Minimal Reproducible Example

https://ota-meshi.github.io/eslint-plugin-astro/playground/#eJx1VV2P20QU/SuXoGo3wt4k+1GVbLISLEJCoqgSbXnxy8S+tocdz4SZcT6IIu0DSJQKoUoUCcQrEgLE8oK6D/05zaY/gzt2nI3b5CETzz3n3LlzfGc8a4Qqwka34ft+ILm0qGMWIjzQamhgFkgAy63ALhiruUxOAzkPZCBDJY2FWQnCHPrwARHUwdDpTis8Q8s+kbEieDPV3s1/T19fPd/zXCxCE2o+tFxJQl5dX766/nPx5IflX1eLF78v/3i6uP5u+es3N99f3vx2tfz7p9f//FvqLnA6VjoyLt0G6MFK/PJy8eMzD5Yvf6YkN89/odGDL3AAFbJeZPHtiz3aFlVdmBDI3juRCu10iJDaTJxRwP2DYDLpBw2UQePMVdBLkUXFEz27rUKYMm3QEunRw4/9e0EDWjVcsgwJLGwgkEyyKG1/Vvl0UCDz7aoNo7ZqN/AdGSrLtsorcIdWq4Gym8qgwWWEEw9iJYQav7XX1Nqhj1/lfETU81LkPyRTazksTmzLuXu6Ni+38W7r3DvIWVJPcp5yiQZ3aTSOuOHWZzF1d03YgYhNzS4dy22q6oJzxo1e8bcoRhzHQ6VtTTPmkU37ERURol9MPMgNat+ETLCBwL5UHnDJLWeiCGK/c9D2IGMTnuVZLUS0bSES5nxzH4LLC9Ao3GsKi4Zx/exmGbnXMqPkvUkmKJxqjCncitnIEQ8I2eVHghI1szVLZuWxX0Mb3VP08tmsbOleq5wW56a1Pji9gYqmlcAIZVfyXmsF9FrVETR2SjcNN91EqAETBa2rFUlmpd73WRhSTV3oHN314OSeB4dHx6d10Bc8SYlyeHhMcNsNJ+03ORHTF104ft+DTtv9Om8SEs0iXixFPiPT68B+SQQ4Pokw8aqZTgb7I6b3qwTN5k6oLLDZhKP2nTVpnHKLcLd9pww0i3rmbiguppUBMb0TP2YZF1O6rqfGYkZd4YFh0vjUcDxe7WPAwotEq1xGXXi3c9Q56bC3EN/wr7HwaTi5Xc59LLYtVxV6H6VQ67LvK8nC2+mnecgjBnQXGCXwNswHrnfo2nKCW/pH+CV7nMPnVH0d+JBbajpkGTwm4RbCuco1Rw2f4Xgdy4hghvRpqzbTaxUdddaY/w+4JmlJ

**Comment by ota-meshi** [comment]
Hmm... The `<style>` tag must be inside the `<head>` tag. Otherwise, the astro parser does not seem to generate an AST of the original structure.

**Comment by GreedyWhale** [comment]
> Hmm... The `<style>` tag must be inside the `<head>` tag. Otherwise, the astro parser does not seem to generate an AST of the original structure.

When I moved the style to the head, the error disappeared, thanks!
