### ISSUE TITLE
New rule for client:only directive to have a value depending on the framework used

### ISSUE THREAD

**Issue by oanaOM** [ota-meshi/eslint-plugin-astro#316]
### Motivation

Whenever using the `client:only` directive, I always forget to pass in a value of the framework. Per Astro docs, is required to pass in a value: https://docs.astro.build/en/reference/directives-reference/#clientonly

### Description

I always remind myself of this after doing several tests and wondering why the rendering of the component is off so I think it's worth adding a rule for this requirement. 

### Examples

```astro
---
---

{/* ✓ GOOD */}
<Foo />
   <Bar client:only="react"/>
<Foo />

{/* ✗ BAD */}
<Foo />
  <Bar client:only/>
<Foo />
```

### Additional comments

I'm happy to contribute by adding this if this is something other people are facing?

**Comment by ota-meshi** [comment]
Thank you for suggesting the rule!
That rule sounds good to me.  Pull requests are welcome.

**Comment by oanaOM** [comment]
Great! I've started working on the changes, have a WIP PR but I get permissions errors when trying to push:
![image](https://github.com/ota-meshi/eslint-plugin-astro/assets/15228388/e2a46f0d-d201-4a0b-a4e4-5e27a9ab9a08)
 
 Could you please let me know how can I get permissions to contribute to this repo?

**Comment by ota-meshi** [comment]
🤔 I think you need to fork this repo.
