### ISSUE TITLE
Add new rule: disallow-exports-from-components

### ISSUE THREAD

**Issue by thehereward** [ota-meshi/eslint-plugin-astro#330]
### Motivation

I am new to astro and ran into a slightly difficult to diagnose issue relating to [this issue](https://github.com/withastro/astro/issues/7264). While I was eventually able to identify and remove the problem it was non-obvious and took a fair amount of time. 

### Description

The rule should disallow any uses of the `export` keyword in an Astro component's component script/frontmatter if **values** are being exported.

Using the `export` keyword with **types** should still be permitted.

I expect this should probably be part of the `astro/base` or `astro/recommended` default configurations.

### Examples

```astro
---
{/* ✓ GOOD */}
const testConst = "some const"
function testFunc () {
    return "some func"
}
export type MyType = string | number

{/* ✗ BAD */}
export const testConst = "some const"
export function testFunc () {
    return "some func"
}
---

```

### Additional comments

I don't know if this is within the scope of what this library should do, but I thought I'd ask before working on a PR.

(I also may have completely misunderstood the underlying issue, but I _hope_ not.)

**Comment by ota-meshi** [comment]
Regarding the rule name, `disallow` is not often used in ESLint rules in my experience. I think `no-exports-from-components` is probably better.

**Comment by thehereward** [comment]
`no-exports-from-components` it is then. (I'd inadvertently copied from the _description_ rather than the rule ID in the rule list docs. 🤦)

I _may_ have time to try to put a PR together next week.

**Comment by Princesseuh** [comment]
Note that exporting types from an Astro component is a totally valid and supported pattern, so this rule should probably allow disallowing only bexporting values.

**Comment by thehereward** [comment]
I've updated the description to include @Princesseuh's comment. Thank you for stopping us making a mistake!
