### ISSUE TITLE
Docs: Mention `"eslint.experimental.useFlatConfig"` for IDE Settings

### ISSUE THREAD

**Issue by lewxdev** [ota-meshi/eslint-plugin-astro#338]
In the [Editor Integrations - Visual Studio Code](https://ota-meshi.github.io/eslint-plugin-astro/user-guide/#visual-studio-code) section of the docs it fails to mention the following configuration

```jsonc
// .vscode/settings.json
{
  // ...
  "eslint.experimental.useFlatConfig": true
}
```

It appears to be necessary for the latest version (I am running `v2.4.4`) of the extension to get lint problems to show in the editor. This may not be necessary in the future, as there is an existing pre-release for `v3`+ that moves this out of "experimental" see [the release notes on the extension](https://github.com/microsoft/vscode-eslint/blob/main/README.md#version-303---pre-release)

Reasoning: The docs currently recommend using the flat config and should at least mention how to get it fully working in Visual Studio Code. (plus, it took me too long to figure out I needed this in my project 😅)

**Comment by ota-meshi** [comment]
I don't think there is any need to explain the experimental settings. The flat config is not recommended as it is not yet GA. It is better to wait for the release of ESLint v9.

**Comment by lewxdev** [comment]
ESLint v9 is out

**Comment by ota-meshi** [comment]
I don't think `eslint.experimental.useFlatConfig` is needed in ESLint v9.
