### ISSUE TITLE
no-shadow in astro file

### ISSUE THREAD

**Issue by cdtut** [ota-meshi/eslint-plugin-astro#339]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.57.0

### What version of `eslint-plugin-astro` are you using?

0.33.1

### What did you do?

Try define a variable called `global` in js file and astro file.

### What did you expect to happen?

`no-shadow` error in both files.

### What actually happened?

Only error in js file.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-1o5lsw

**Comment by ota-meshi** [comment]
Please DON'T USE stackblitz as a repro.
We can't debug eslint with stackblitz.
