### ISSUE TITLE
feat: Documentation for Manual Flat Config Setup

### ISSUE THREAD

**Issue by Mitsunee** [ota-meshi/eslint-plugin-astro#370]
### Description

I am having issues setting up eslint-plugin-astro with my existing configurations for TypeScript and would like to manually configure the plugin and parser (but also use the recommended ruleset) but cannot find documentation for how to include the parser or get the ruleset to include in my own configuration.

My current approach to this seems very unstable as I am using Array.find to grab the parts I need from the recommended config:

```ts
// base configs
const __dirname = new URL(".", import.meta.url).pathname.slice(0, -1);
/* ... */

// astro configs
const astroLangOpts = pluginAstro.configs.recommended.find(cfg =>
  cfg.files?.includes("**/*.astro")
).languageOptions;
const astroRules = pluginAstro.configs.recommended.find(
  // this especially seems like a really bad idea tbh:
  cfg =>
    cfg.rules &&
    !cfg.rules["prettier/prettier"] &&
    Object.keys(cfg.rules).length > 1
).rules;
// fix typescript parserOptions (languageOptions.parserOptions.parserOptions)
Object.assign(astroLangOpts.parserOptions, {
  parserOptions: { project: "tsconfig.json", tsconfigRootDir: __dirname }
});
const astroConfig = {
  files: ["**/*.astro"],
  plugins: { astro: pluginAstro },
  languageOptions: astroLangOpts,
  rules: Object.assign({}, astroRules, {
    "react/jsx-filename-extension": "off",
    "react/no-unknown-property": "off",
    "react/no-unescaped-entities": "off",
    "react/jsx-key": "off"
  })
};
```

I am already including `**/*.astro/*.ts` in my existing typescript configuration by pushing that pattern to the files array, same for js. Futhermore I'm including `**/*.astro` in my (p)react configuration, so I need to disable some react plugin rules as seen above.

**Comment by ota-meshi** [comment]
If you don't like the config provided by this plugin, I recommend building your preferred config entirely from scratch.

**Comment by Mitsunee** [comment]
> If you don't like the config provided by this plugin, I recommend building your preferred config entirely from scratch.

yes I am asking for documentation to do just that

**Comment by ota-meshi** [comment]
I don't understand what you mean.
The purpose of this plugin is to enable linting with ESLint for astro files. To do so, just configure the plugin and parser.

**Comment by Mitsunee** [comment]
Yes I would like to do so, however there is no documentation for manually configuring the plugin and parser.

**Comment by ota-meshi** [comment]
> however there is no documentation for manually configuring the plugin and parser.

here it is.


https://eslint.org/docs/latest/use/configure/plugins
https://eslint.org/docs/latest/use/configure/parser

**Comment by Mitsunee** [comment]
I am asking for how to import this specific plugin and parser. Please stop trolling me.
