### ISSUE TITLE
new rule `no-exports-from-components` needs exeptions

### ISSUE THREAD

**Issue by TheElegantCoding** [ota-meshi/eslint-plugin-astro#385]
Astro has some functions that can be exported in a file and has some logic with it 

for example, in dynamic routing, we use getStaticPath to define the correct matching routes and this function has to have "export" inside the file.

i don't know if there more exceptions like this, the plugin could have exceptions for this cases and also for other specials cases

- https://docs.astro.build/en/reference/api-reference/#getstaticpaths

**Comment by ota-meshi** [comment]
Thank you for the report.
It appears that `export const prerender = true;` is also allowed.
https://docs.astro.build/en/guides/server-side-rendering/#opting-in-to-pre-rendering-in-server-mode
I don't know if there are more. How should I find out?...

**Comment by ota-meshi** [comment]
For now, I've changed the rule to allow `getStaticPaths` and `prerender`.
If you find anything else that needs to be excluded, please open a new issue.
