### ISSUE TITLE
docs: update typescript-eslint suggestion?

### ISSUE THREAD

**Issue by braden-w** [ota-meshi/eslint-plugin-astro#404]
According to the [typescript-eslint v7 release notes](https://typescript-eslint.io/blog/announcing-typescript-eslint-v7/#new-features---flat-config-support), it seems that `@typescript-eslint/parser` is no longer recommended in flat configs, but rather just `typescript-eslint`.

> Because this new package includes dependencies on our plugin and parser, you can replace those dependencies entirely:
> 
> ```
> pnpm remove @typescript-eslint/parser @typescript-eslint/eslint-plugin
> pnpm add typescript-eslint
> ```
> 
> The simplest of this new tooling would be the following which will enable the ESLint recommended config and our recommended config (including turning on our plugin and parser):
> 
> 
> 
> ```
> // @ts-check
> 
> import eslint from '@eslint/js';
> import tseslint from 'typescript-eslint';
> 
> export default tseslint.config(
>   eslint.configs.recommended,
>   ...tseslint.configs.recommended,
> );
> ```

Just wanted to double check if the installation instructions in the readme should be updated accordingly or not.

**Comment by Xifong** [comment]
Does that mean our config should look like the following?

```
import eslintPluginAstro from 'eslint-plugin-astro';
import tseslint from 'typescript-eslint';

export default [
  // add more generic rule sets here, such as:
  // js.configs.recommended,
  ...eslintPluginAstro.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      // override/add rules settings here, such as:
      // "astro/no-set-html-directive": "error"
    },
  },
];
```
That leads to a `Class extends value undefined is not a constructor or null` and I'm not sure what the config should actually look like to get a flat config for parsing typescript astro components working.
