### ISSUE TITLE
Sort Attributes rule

### ISSUE THREAD

**Issue by azat-io** [ota-meshi/eslint-plugin-astro#417]
### Motivation

Hello!

ESLint Plugin Perfectionist plans to deprecate from rules that use third-party parsers (https://github.com/azat-io/eslint-plugin-perfectionist/issues/175).

We'd like to move a rule to you for sorting Astro element attributes.

### Description

This rule is needed to sort attributes and create a consistent codebase style.

The rule should be able to sort attributes alphabetically and by line length. Sorting by descending and ascending should also be supported.

The rule should take into account spreads within Astro elements.

### Examples

```astro
---
---

{/* ✓ GOOD */}
<Foo a="aaa" b="bb" c="c" />

{/* ✗ BAD */}
<Foo b="bb" c="c" a="aaa" />
```

**Comment by ota-meshi** [comment]
Thank you for posting the issue!
It SGTM that we can provide that rule from this plugin.

**Comment by tunnckoCore** [comment]
@ota-meshi @azat-io i don't see that to be working. In addition to that i'm getting parsing error on script tags even without types there.

**Comment by azat-io** [comment]
@tunnckoCore Could you show more details? Your settings, code and error message.
