### ISSUE TITLE
breaks `eslint-plugin-simple-import-sort`

### ISSUE THREAD

**Issue by stefanprobst** [ota-meshi/eslint-plugin-astro#92]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.21.0

### What version of `eslint-plugin-astro` are you using?

0.17.1

### What did you do?

I want to use `eslint-plugin-astro` together with `eslint-plugin-simple-import-sort` to sort imports in astro frontmatter.

this works fine as long as import statements end with a semicolon. for example:

```astro
---
import Card from '@/components/card.astro';
import Layout from '@/layouts/page.layout.astro';
---
```

![Screenshot_20220813_194918](https://user-images.githubusercontent.com/20753323/184505168-a7dbf172-af47-44a5-a0d9-40a08dba6b12.png)

however, when i omit trailing semicolons, i get an unfixable error:

```astro
---
import Card from '@/components/card.astro'
import Layout from '@/layouts/page.layout.astro'
---
```

![Screenshot_20220813_195216](https://user-images.githubusercontent.com/20753323/184505272-cbfdd571-0aec-4079-a2b8-af9333c72445.png)

the reason this fails is because `eslint-plugin-simple-import-sort` [compares](https://github.com/lydell/eslint-plugin-simple-import-sort/blob/main/src/shared.js#L49) the following (note the trailing newline character), which will always fail:

![Screenshot_20220813_200221](https://user-images.githubusercontent.com/20753323/184505595-818289ad-844b-4922-867e-8ce65f8da59b.png)

this is because the second import statement gets parsed into a `ImportDeclaration` node, whose `loc` includes the first char of the next line, i.e. `loc.start.line` is 3 and `loc.end.line` is 4:

![Screenshot_20220813_195818](https://user-images.githubusercontent.com/20753323/184505453-f8dbf700-4268-43d0-be2d-f6f5a485b86f.png)

i *think* this happens because what the typescript-eslint parser [sees](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/parser/src/parser.ts#L81) is:

```ts

import Card from '@/components/card.astro'
import Layout from '@/layouts/page.layout.astro'
;
```

whereas when using semicolons, it sees:

```ts

import Card from '@/components/card.astro';
import Layout from '@/layouts/page.layout.astro';
;
```

apparently, these get parsed differently:

![Screenshot_20220813_202942](https://user-images.githubusercontent.com/20753323/184506386-c822cc24-12c5-4ced-aae5-bce6211807c4.png)

<details>
<summary>Configuration</summary>

```
{
  "eslintConfig": {
    "root": true,
    "reportUnusedDisableDirectives": true,
    "extends": [
      "eslint:recommended",
      "plugin:@typescript-eslint/recommended",
      "plugin:import/recommended",
      "plugin:import/typescript",
      "prettier"
    ],
    "plugins": ["simple-import-sort"],
    "rules": {
      "import/first": "error",
      "import/newline-after-import": "error",
      "import/no-anonymous-default-export": "error",
      "import/no-duplicates": "error",
      "simple-import-sort/imports": "error"
    },
    "settings": {
      "import/parsers": {
        "@typescript-eslint/parser": [".ts", ".tsx"]
      },
      "import/resolver": {
        "typescript": {
          "alwaysTryTypes": true
        }
      }
    },
    "overrides": [
      {
        "files": ["*.astro"],
        "extends": [
          "plugin:astro/recommended",
          "plugin:astro/jsx-a11y-recommended"
        ],
        "parser": "astro-eslint-parser",
        "parserOptions": {
          "parser": "@typescript-eslint/parser",
          "extraFileExtensions": [".astro"]
        }
      }
    ]
  }
}
```
</details>

### What did you expect to happen?

sorted imports also when not using semicolons

### What actually happened?

unfixable eslint error

### Link to Minimal Reproducible Example

https://github.com/stefanprobst/issue-eslint-astro

issue is visible in `src/pages/index.astro`

**Comment by ota-meshi** [comment]
Thank you for the posting the issue and detailed information!

I will look into how to fix it.

**Comment by ota-meshi** [comment]
It was a parser issue, so I fixed the parser and released it. Please update astro-eslint-parser to the latest.

https://github.com/ota-meshi/astro-eslint-parser/releases/tag/v0.5.1

**Comment by stefanprobst** [comment]
thanks for the quick fix!
