### ISSUE TITLE
Parsing error with inline script tags

### ISSUE THREAD

**Issue by cj** [ota-meshi/eslint-plugin-astro#95]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.22.0

### What version of `eslint-plugin-astro` are you using?

0.17.1

### What did you do?

<details>
<summary>Configuration</summary>

https://gist.github.com/cj/c82422a88af4d3afd7afb828cdf903c2
</details>

https://gist.github.com/cj/08f13d06699b71bed821f01d39d50202

### What did you expect to happen?

For there to be no validation issue

### What actually happened?

A parsing error happened.

<img width="775" alt="image" src="https://user-images.githubusercontent.com/1819/185804876-42d73c34-1d05-41a0-9f96-13413b1be912.png">

### Link to Minimal Reproducible Example

https://github.com/cj/eslint-plugin-astro-script-parsing-error

### Additional comments

https://docs.astro.build/en/core-concepts/astro-components/#client-side-scripts

**Comment by ota-meshi** [comment]
It has been reported that prettier parsing fails with `prettier/prettier` rule. As the docs say, the rule should be turned off.

https://github.com/ota-meshi/eslint-plugin-astro#:~:text=%22prettier/prettier%22%3A%20%22off%22%2C

**Comment by cj** [comment]
@ota-meshi even with it turned off I get the error:

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/1819/185843895-00076b35-e4ec-43ba-9dc3-502dc15e37c4.png">

**Comment by ota-meshi** [comment]
You are specifying the wrong part.
Specify in `files: ["**/*.astro/*.js", "*.astro/*.js"],`.

**Comment by cj** [comment]
@ota-meshi ah, I needed it in both places. Thank you!
